import AsyncStorage from "@react-native-async-storage/async-storage";
import { createClient } from "@supabase/supabase-js";
import Constants from "expo-constants";
import "react-native-url-polyfill/auto";

// Get Supabase credentials from environment variables
const supabaseUrl = Constants.expoConfig?.extra?.supabaseUrl || "";
const supabaseAnonKey = Constants.expoConfig?.extra?.supabaseAnonKey || "";

if (!supabaseUrl || !supabaseAnonKey) {
	console.warn(
		"Supabase credentials not configured. Please add EXPO_PUBLIC_SUPABASE_URL and EXPO_PUBLIC_SUPABASE_ANON_KEY to your environment variables.",
	);
}

// Create Supabase client with AsyncStorage for session persistence
export const supabase = createClient(supabaseUrl, supabaseAnonKey, {
	auth: {
		storage: AsyncStorage,
		autoRefreshToken: true,
		persistSession: true,
		detectSessionInUrl: false,
	},
});

// Helper function to get the current user's session
export async function getSession() {
	const {
		data: { session },
		error,
	} = await supabase.auth.getSession();
	if (error) {
		console.error("Error getting session:", error);
		return null;
	}
	return session;
}

// Helper function to get the current user
export async function getCurrentUser() {
	const {
		data: { user },
		error,
	} = await supabase.auth.getUser();
	if (error) {
		console.error("Error getting user:", error);
		return null;
	}
	return user;
}

// Helper function to sign out
export async function signOut() {
	const { error } = await supabase.auth.signOut();
	if (error) {
		console.error("Error signing out:", error);
		throw error;
	}
}

// Database type definitions (will be auto-generated by Supabase CLI in production)
export type Database = {
	public: {
		Tables: {
			profiles: {
				Row: {
					id: string;
					email: string;
					name: string | null;
					avatar_url: string | null;
					preferences: any | null;
					created_at: string;
					updated_at: string;
				};
				Insert: {
					id: string;
					email: string;
					name?: string | null;
					avatar_url?: string | null;
					preferences?: any | null;
					created_at?: string;
					updated_at?: string;
				};
				Update: {
					id?: string;
					email?: string;
					name?: string | null;
					avatar_url?: string | null;
					preferences?: any | null;
					created_at?: string;
					updated_at?: string;
				};
			};
			scenarios: {
				Row: {
					id: string;
					user_id: string;
					title: string;
					description: string;
					category: string;
					duration: number;
					difficulty: string | null;
					image_url: string | null;
					tags: string[] | null;
					persona: any | null;
					is_custom: boolean;
					created_at: string;
					updated_at: string;
				};
				Insert: {
					id?: string;
					user_id: string;
					title: string;
					description: string;
					category: string;
					duration: number;
					difficulty?: string | null;
					image_url?: string | null;
					tags?: string[] | null;
					persona?: any | null;
					is_custom?: boolean;
					created_at?: string;
					updated_at?: string;
				};
				Update: {
					id?: string;
					user_id?: string;
					title?: string;
					description?: string;
					category?: string;
					duration?: number;
					difficulty?: string | null;
					image_url?: string | null;
					tags?: string[] | null;
					persona?: any | null;
					is_custom?: boolean;
					created_at?: string;
					updated_at?: string;
				};
			};
			feedback_sessions: {
				Row: {
					id: string;
					user_id: string;
					scenario_id: string;
					score: number;
					completed_at: string;
					duration: number;
					transcript: any | null;
					analysis: any | null;
					created_at: string;
				};
				Insert: {
					id?: string;
					user_id: string;
					scenario_id: string;
					score: number;
					completed_at?: string;
					duration: number;
					transcript?: any | null;
					analysis?: any | null;
					created_at?: string;
				};
				Update: {
					id?: string;
					user_id?: string;
					scenario_id?: string;
					score?: number;
					completed_at?: string;
					duration?: number;
					transcript?: any | null;
					analysis?: any | null;
					created_at?: string;
				};
			};
			documents: {
				Row: {
					id: string;
					name: string;
					description: string | null;
					tags: string[] | null;
					type: string;
					size: number | null;
					url: string | null;
					created_at: string;
					updated_at: string;
				};
				Insert: {
					id?: string;
					name: string;
					description?: string | null;
					tags?: string[] | null;
					type: string;
					size?: number | null;
					url?: string | null;
					created_at?: string;
					updated_at?: string;
				};
				Update: {
					id?: string;
					name?: string;
					description?: string | null;
					tags?: string[] | null;
					type?: string;
					size?: number | null;
					url?: string | null;
					created_at?: string;
					updated_at?: string;
				};
			};
			persona_queue: {
				Row: {
					id: string;
					scenario_id: string;
					persona_input: any;
					status: string;
					attempts: number;
					error: string | null;
					created_at: string;
					updated_at: string;
				};
				Insert: {
					id?: string;
					scenario_id: string;
					persona_input: any;
					status?: string;
					attempts?: number;
					error?: string | null;
					created_at?: string;
					updated_at?: string;
				};
				Update: {
					id?: string;
					scenario_id?: string;
					persona_input?: any;
					status?: string;
					attempts?: number;
					error?: string | null;
					created_at?: string;
					updated_at?: string;
				};
			};
		};
	};
};
